use test;

create external table test.test (
screenSize string,
sub string,
callerOriPkg string,
apptag string,
appid string,
valong double,
inputName string,
resolution string,
manufact string,
recResult string,
city string,
os_type string,
`timestamp` double,
dvc_model string,
manufactLable string,
ntt string,
inputType string,
age string,
province string,
gender string,
callerOriName string,
appOriName string,
sid string,
apptagID string,
dvc string,
inputPkg string,
valat double,
caller_appid string,
did string,
operator string,
country string,
os_version string,
appOriPkg string,
appname string,
imei string,
mac string,
idfa string,
openudid string,
imsi string,
clientIp string,
dvcModelLable string
)
stored as orc
location '/user/ylzhang5/extract/VCOAMDataClean/2016-05-14/orc/';
